### ISSUE TITLE
Feature request: battery info for all system batteries

### ISSUE THREAD

**Issue by valderman** [taffybar/taffybar#148]
Taffybar currently only gets battery info for the first battery found. This is quite inconvenient for recent ThinkPads, which have two batteries. Would it be possible to get battery info for _all_ system batteries instead of a semi-randomly chosen one?

**Comment by IvanMalison** [comment]
@valderman This is sort of fixed in 72ab4290adcbce761823d7c15393a63e54b1da57

because we've switched to using the "DisplayDevice" for getting battery info (see https://upower.freedesktop.org/docs/UPower.html#UPower.GetDisplayDevice) This aggregates information from all batteries.

Is this the sort of thing you had in mind, or do you want to be able to actually view separate information about each battery separately?

**Comment by IvanMalison** [comment]
@valderman I consider this fixed. You can reopen this or file a new issue if you actually want separate information for each battery, as opposed to information about all of them collectively
