### ISSUE TITLE
Use Proper Broadcast channel/0 reader spaceleak

### ISSUE THREAD

**Issue by IvanMalison** [taffybar/taffybar#352]
such as https://github.com/merijn/broadcast-chan

the current approach (that uses dupChan to simulate a broadcast channel has a zero reader space leak)

**Comment by amurrayc** [comment]
What would be the desired behaviour for shared channels?  At the moment, each widget (at least the ones created by `channelWidgetNew` and `channelGraphNew`) has its own channel that connects to an information source.  Would the idea be to allow two related widgets (like a battery icon and a battery text widget) to share an information source?

Wouldn't most widgets have independent sources?

**Comment by IvanMalison** [comment]
> What would be the desired behaviour for shared channels? At the moment, each widget (at least the ones created by `channelWidgetNew` and `channelGraphNew`) has its own channel that connects to an information source. Would the idea be to allow two related widgets (like a battery icon and a battery text widget) to share an information source?

As I mentioned in your pull request, this is not correct. They all share a channel because the value is retrieved through `getStateDefault`, which ensures that there is only one value that is retrieved every time whatever the relevant get function is called.

**Comment by IvanMalison** [comment]
> Wouldn't most widgets have independent sources?

Yes, most widgets have independent sources (although not all e.g. battery graph or icon and battery percentage), but people with multiple displays (and multiple taffybars) are going to have multiple instances of the same widget. The current implementation uses a channel and a single source for information retrieval, but updates all of the widgets for each new piece of data.

**Comment by IvanMalison** [comment]
> They all share a channel because the value is retrieved through `getStateDefault`, which ensures that there is only one value that is retrieved every time whatever the relevant get function is called.

I should clarify that they each have their own read end of the channel, but they share the write end of the channel.

**Comment by IvanMalison** [comment]
@amurrayc if you want to spearhead migrating all of our channels to https://github.com/merijn/broadcast-chan I would greatly appreciate it.

I think the reason I didn't take it on myself was that I was a little worried that it doesn't seem to have all that much community support, but maybe we can help with that I guess.

**Comment by amurrayc** [comment]
I've done a pretty simple switch to broadcast-chan in the abovementioned fork. It's in the broadcast-chan branch.

As far as I can tell, in the Chan-based approach, the first listener creates the information channel but then it, and all subsequent listeners `dupChan` and then start reading. That means there are n+1 channels but only n listeners. Am I missing something?

Anyway, now the first channel creates a `BroadcastChan In` for writing and then it, and each subsequent listener `newBChanListener` their way to obtaining a receiving end.

The space leak I was getting seems to be gone. (I have a very chatty battery - not sure if it's normal to be getting status updates from it every second or so but it certainly highlights the problem quickly)

At the moment I'm ignoring the return value of `writeBChan`. Perhaps logging failures would be useful.

I haven't done anything with the `Chan`s in `SafeX11.hs` yet since it is more complex and I've run out of time today.

I'd be glad for any feedback.  I'm fairly new to the github flow so excuse me if I'm a bit klutzy for now.

**Comment by amurrayc** [comment]
Also, the changelog for broadcast-chan says "Complete rework to be actually practical." for version 0.2.0.

This is only in stackage nightlies as far as I can tell.

**Comment by IvanMalison** [comment]
> This is only in stackage nightlies as far as I can tell.

Not really a problem. Just need to be published to hackage.

@amurrayc Any chance you want to make a pull request?

**Comment by amurrayc** [comment]
Absolutely.  Sorry for the delay: life and computer failure got in the way.

I'm just looking over the modifications to check they still make sense.  (Also I see some new channel stuff in Information/Chrome.hs which I will look at too.)

**Comment by IvanMalison** [comment]
@amurrayc Is the code in that branch ready to go? I can pick it up from here if you want.

**Comment by amurrayc** [comment]
Just about to push a tidier version.  Later today.

**Comment by IvanMalison** [comment]
#472 may have also been the cause of a leak
