### ISSUE TITLE
No Visible SNITray

### ISSUE THREAD

**Issue by nrdxp** [taffybar/taffybar#376]
**Describe the bug**
When launching taffybar, I am unable to see any tray icons for programs that should have them, they show up properly in trayer for example.

**To Reproduce**
set tray to sniTrayNew, start status-notifier-watcher, start taffybar, no systray icons are visible and the space where it should be is empty

**Expected behavior**
systray icons should be visible and interactable

**Screenshots**
I think problem is simple enough to go without screenshotting it

**Version information**
Taffybar version (or git sha if building from source): 2.1.1
Installation method (nix/stack/cabal/arch packages): aur package
Gtk version: 3.22.30

**Comment by IvanMalison** [comment]
@nrdxp SNITray != XEMBED tray, which is what trayer is.

The XEMBED protocol is deprecated and it has a ton of problems.

If you want xembed tray items to show with the sni tray you can use
https://github.com/KDE/plasma-workspace/tree/master/xembed-sni-proxy

if you still want an xembed tray you can use the systray module.

**Comment by IvanMalison** [comment]
@nrdxp Sorry if my response wasn't clear, but basically the likely reason there are no tray icons visible is that you have not set up any appindicator/snitray programs. A lot of programs can actually be configured to use this protocol instead of xembed. take a look at their command line flags.

You should read the documentation of https://github.com/taffybar/gtk-sni-tray#statusnotifierwatcher
