### ISSUE TITLE
unhelpful Workspaces error

### ISSUE THREAD

**Issue by clinty** [taffybar/taffybar#447]
A config that works fine on one machine fails on another with

```
taffybar-linux-x86_64: Prelude.read: no parse
```

Removing `workspacesNew defaultWorkspacesConfig` as a startWidget makes that error go away.  Why?

**Comment by IvanMalison** [comment]
@clinty I'm getting this now as well and investingating. I think it may have to do with ghc version for some reason, since I wasn't having this issue until I started using the newest version of ghc.

@clinty Can you tell me what you are using to compile taffybar?

**Comment by clinty** [comment]
GHC 8.4.4

**Comment by IvanMalison** [comment]
@clinty your original title was kind of passive aggresive btw. The error arose because an unsafe function (read) was being used when parsing DesktopEntries, taffybar does not have control over what this error looks like.

This error should only appear for people that have a XDGDesktopEntry that can't be Read as this datatype, which is why it hasnt been encountered until recently.
```
data DesktopEntryType = Application | Link | Directory
  deriving (Read, Show, Eq)
```
