### ISSUE TITLE
Battery widget can hang on startup

### ISSUE THREAD

**Issue by travitch** [taffybar/taffybar#45]
This is related to #44.  Most of the battery widget code runs in its own thread, but some initialization code (that apparently can hang indefinitely) runs in the main thread at taffybar startup time.  This code (`batteryContextNew`) should be moved to a separate thread or have a timeout.

**Comment by codygman** [comment]
@travitch Did you ever do this? This seems like exactly the type of thing you would use stm for.

**Comment by travitch** [comment]
I haven't worked on this yet.  Looking back at the code, I think a simple mvar would be sufficient.  The idea would be to just set up the Gtk widget and have the polling function block on an mvar until it is filled in by a separate initialization thread.

That said, I haven't heard of any problems with this code since the bug was reported.

**Comment by IvanMalison** [comment]
We can use an approach similar to https://github.com/taffybar/taffybar/blob/337f131d1ee1e115600a375ce00b7a596ca302b6/src/System/Taffybar/DBus/Toggle.hs#L97

To only get this dbus connections at the point that it is actually needed (i.e. after widget initialization). This will also help us share the system dbus connection.

**Comment by IvanMalison** [comment]
As of 72ab4290adcbce761823d7c15393a63e54b1da57, there is no BatteryContext, and no initialization of the dbus client occurs in the construction of the battery widget, so I would consider this issue to be fixed.

The battery widget is simply using the systemDbusClient provided by context, which IS still technically on the main thread at startup.

The issue described here https://github.com/taffybar/taffybar/issues/44#issuecomment-22069665

would no longer be an issue because we fork before we do any actual communication with upower:

https://github.com/taffybar/taffybar/blob/fbec14c85004eef0aa11ebb78256ce2877f3f0d5/src/System/Taffybar/Information/Battery.hs#L189

> Looking back at the code, I think a simple mvar would be sufficient.

Agreed, This is actually what the state mechanism that stores the channel and mvar for batteryInfo.
