### ISSUE TITLE
Installation fails on Arch Linux

### ISSUE THREAD

**Issue by noaccOS** [taffybar/taffybar#501]
**Describe the bug**
When trying to install taffybar, both from the AUR and from source, the installation fails on the installation of gi-glib

**To Reproduce**
Try to install taffybar on Arch Linux. I had to allow newer packages in the stack configuration or it wouldn't let me continue.

**Expected behavior**
Taffybar installs

**Screenshots**
![image](https://user-images.githubusercontent.com/24324352/94336483-dab25200-ffe3-11ea-9b06-0ccedc70990b.png)

**Version information**
Taffybar version (or git sha if building from source): 3.2.2-1
Installation method (nix/stack/cabal/arch packages): AUR/Stack/Cabal
Gtk version: 1:3.24.23-1

**Comment by illis** [comment]
I'm on Arch Linux. Seems to be building for me using nix+cabal.  Not quite on a clean system, so not sure if it will be reproducable for you; but try:
`nix-shell ./shell.nix --run "cabal v2-build"`

**Comment by IvanMalison** [comment]
@illis nix will always work on pretty much any system because you know, reproducible builds.

@noaccOS What resolver are you using. Can you post your stack.yaml?

**Comment by noaccOS** [comment]
My partition died so I decided to give NixOS a try.
BTW seems like the error pops up on other programs too, i found https://github.com/cdepillabout/termonad/issues/169 for termonad (the fix mentioned didn't work for me)

@IvanMalison I used yay to install it, the stack.yaml is the one from the aur

**Comment by IvanMalison** [comment]
@noaccOS This is why I have this caveat listed in the README:

> Several linux distributions package taffybar (nixos, arch/aur, debian). Of these, only the NixOS distribution is officially supported by the maintainers.

And why I opposed any packaging of taffybar for arch linux in the first place.

Also see the discussions here:

https://github.com/taffybar/taffybar/issues/151

**Comment by IvanMalison** [comment]
@noaccOS IMO it sucks that many arch users end up encountering the aur package first, and MUCH of the time, it simply does not work, for a variety of reasons.

**Comment by illis** [comment]
Haskell on Arch is messed up, if your using anything but the stock Arch packages.  I found using nix on top of arch is the only reliable solution. 

I wonder if its worth making nix a dependency in the AUR pkgbuild? Or having a separate package along the lines of `taffybar-git-nix' in the aur?

**Comment by LeifW** [comment]
I'm not using taffybar anymore, but I was thinking to switch the AUR PKGBUILD to use ghc-static + ghc-pristine, and do a cabal new-build of taffybar - so it wouldn't have external (Haskell) dependencies.

**Comment by guygastineau** [comment]
I use `stack` for all of my Haskell tools on Arch.  I used to use `Nix` on top of Arch, but it doesn't always work out as well as I would like, so I have stopped.

I wonder if this build failure is at all related to some upstream issues with `gi-gtk` and `haskell-gi`?  There was a bug fix in the latter half of last year, and a bunch of builds broke due to version constraints.  The most recent nightly resolver helps obviate the need for a bunch of `extra-deps` specification in a `stack.yaml`, but that is not a great permanent fix.  Once the `gi-*` changes have gone into an lts resolver stack users should be quite comfortable.

I fixed a build issue for [gi-gtk-declarative](https://github.com/owickstrom/gi-gtk-declarative).  You can see the changes I had to make to the cabal files in [this diff](https://github.com/owickstrom/gi-gtk-declarative/pull/90/files).  Hopefully this helps, maybe it wont.

BTW, if anyone here likes the `nix` programming language and would like to help, the PR linked above is failing its Travis build, because the nix file is messed up.  Although, Travis is going away soon, and the repo owner should move to GA or something it would still be very nice if it could be fixed for merging.

**Comment by IvanMalison** [comment]
I have requested that the aur package be deleted. I may try to replace it with a nix or stack based installation. Using the arch haskell system has become an untenable proposition for taffybar.

**Comment by milse113** [comment]
I'm also suffering from this issue; is there a temporary solution until a more long-term one is found?

**Comment by IvanMalison** [comment]
> I'm also suffering from this issue; is there a temporary solution until a more long-term one is found?

The solution is to use nix stack or cabal to install.

This is never goi g to work consistently with arch installation

**Comment by milse113** [comment]
I'm suffering from an error with cabal as well; namely with haskell-gi. What do you recommend?

**Comment by IvanMalison** [comment]
The easiest way is to install with nix. Probably the reason things are failing is because you are missing some for files

**Comment by milse113** [comment]
Should I get the Nix package manager specifically to install TaffyBar?

**Comment by IvanMalison** [comment]
@milse113 yes, that is the idea.
